pragma Singleton
import QtCore
import QtQuick

/**
 * The phone app's palettes.
 *
 * GENERATED by desktop/tools/generate-theme.py from mobile/src/theme/colors.ts — edit the
 * colours there and re-run it, not this file. Both apps then show the same thing, which is
 * the whole reason a toolkit that lets us set every colour was chosen.
 *
 * The choice is remembered between runs rather than resetting to the default each launch.
 */
QtObject {
    id: theme

    property string mode: "dark"
    property string variant: "zinc"

    readonly property var darkVariants: [{ "id": "zinc", "label": "Zinc" }, { "id": "slate", "label": "Slate" }, { "id": "crimson", "label": "Crimson" }, { "id": "emerald", "label": "Emerald" }, { "id": "midnight", "label": "Midnight" }, { "id": "ember", "label": "Ember" }, { "id": "carbon", "label": "Carbon" }, { "id": "orchid", "label": "Orchid" }]
    readonly property var lightVariants: [{ "id": "neutral", "label": "Neutral" }, { "id": "warm", "label": "Warm" }, { "id": "cool", "label": "Cool" }, { "id": "paper", "label": "Paper" }, { "id": "frost", "label": "Frost" }]
    readonly property var variants: mode === "dark" ? darkVariants : lightVariants

    readonly property var palettes: ({
        "dark.zinc": { "accent": "#22d3ee", "accentHover": "#06b6d4", "background": "#09090b", "border": "#27272a", "borderSubtle": "#3f3f46", "error": "#ef4444", "info": "#3b82f6", "overlay": "#b2000000", "primary": "#f4f4f5", "primaryHover": "#e4e4e7", "primaryText": "#09090b", "success": "#22c55e", "surface": "#18181b", "surfaceActive": "#3f3f46", "surfaceHover": "#27272a", "text": "#fafafa", "textMuted": "#a1a1aa", "textSubtle": "#71717a", "warning": "#f59e0b" },
        "dark.slate": { "accent": "#60a5fa", "accentHover": "#3b82f6", "background": "#020617", "border": "#1e293b", "borderSubtle": "#334155", "error": "#ef4444", "info": "#3b82f6", "overlay": "#b2020617", "primary": "#e2e8f0", "primaryHover": "#cbd5e1", "primaryText": "#020617", "success": "#22c55e", "surface": "#0f172a", "surfaceActive": "#334155", "surfaceHover": "#1e293b", "text": "#f8fafc", "textMuted": "#94a3b8", "textSubtle": "#64748b", "warning": "#f59e0b" },
        "dark.crimson": { "accent": "#f87171", "accentHover": "#ef4444", "background": "#0a0a0a", "border": "#262626", "borderSubtle": "#404040", "error": "#ef4444", "info": "#3b82f6", "overlay": "#b20a0a0a", "primary": "#dc2626", "primaryHover": "#b91c1c", "primaryText": "#ffffff", "success": "#22c55e", "surface": "#171717", "surfaceActive": "#404040", "surfaceHover": "#262626", "text": "#fafafa", "textMuted": "#a3a3a3", "textSubtle": "#737373", "warning": "#f59e0b" },
        "dark.emerald": { "accent": "#34d399", "accentHover": "#10b981", "background": "#022c22", "border": "#065f46", "borderSubtle": "#047857", "error": "#ef4444", "info": "#3b82f6", "overlay": "#b2022c22", "primary": "#10b981", "primaryHover": "#059669", "primaryText": "#022c22", "success": "#22c55e", "surface": "#064e3b", "surfaceActive": "#047857", "surfaceHover": "#065f46", "text": "#ecfdf5", "textMuted": "#a7f3d0", "textSubtle": "#6ee7b7", "warning": "#f59e0b" },
        "dark.midnight": { "accent": "#7aa2f7", "accentHover": "#5d87e8", "background": "#0f1419", "border": "#212936", "borderSubtle": "#2d3748", "error": "#f7768e", "info": "#7dcfff", "overlay": "#b2000000", "primary": "#e2e8f0", "primaryHover": "#cbd5e1", "primaryText": "#0f1419", "success": "#9ece6a", "surface": "#171d25", "surfaceActive": "#2d3748", "surfaceHover": "#212936", "text": "#e2e8f0", "textMuted": "#94a3b8", "textSubtle": "#64748b", "warning": "#e0af68" },
        "dark.ember": { "accent": "#f0a35e", "accentHover": "#dc8a41", "background": "#1a1512", "border": "#322820", "borderSubtle": "#43352a", "error": "#e26d5c", "info": "#7aa6c2", "overlay": "#b8000000", "primary": "#f5ebe0", "primaryHover": "#e6d7c7", "primaryText": "#1a1512", "success": "#8fb573", "surface": "#241d18", "surfaceActive": "#43352a", "surfaceHover": "#322820", "text": "#f5ebe0", "textMuted": "#b9a48f", "textSubtle": "#8a7663", "warning": "#e6b450" },
        "dark.carbon": { "accent": "#a3e635", "accentHover": "#84cc16", "background": "#000000", "border": "#262626", "borderSubtle": "#404040", "error": "#f87171", "info": "#60a5fa", "overlay": "#cc000000", "primary": "#ffffff", "primaryHover": "#e5e5e5", "primaryText": "#000000", "success": "#4ade80", "surface": "#0d0d0d", "surfaceActive": "#262626", "surfaceHover": "#1a1a1a", "text": "#ffffff", "textMuted": "#a3a3a3", "textSubtle": "#737373", "warning": "#fbbf24" },
        "dark.orchid": { "accent": "#c084fc", "accentHover": "#a855f7", "background": "#14101a", "border": "#2a2136", "borderSubtle": "#382c47", "error": "#ff7a8a", "info": "#8fb8ff", "overlay": "#b8000000", "primary": "#ede9f5", "primaryHover": "#d9d2e8", "primaryText": "#14101a", "success": "#7ee0a8", "surface": "#1e1828", "surfaceActive": "#382c47", "surfaceHover": "#2a2136", "text": "#ede9f5", "textMuted": "#a99fc0", "textSubtle": "#7d7395", "warning": "#f5c56b" },
        "light.neutral": { "accent": "#6366f1", "accentHover": "#4f46e5", "background": "#ffffff", "border": "#e5e5e5", "borderSubtle": "#d4d4d4", "error": "#dc2626", "info": "#2563eb", "overlay": "#80000000", "primary": "#171717", "primaryHover": "#262626", "primaryText": "#ffffff", "success": "#16a34a", "surface": "#f5f5f5", "surfaceActive": "#d4d4d4", "surfaceHover": "#e5e5e5", "text": "#171717", "textMuted": "#525252", "textSubtle": "#737373", "warning": "#d97706" },
        "light.warm": { "accent": "#f97316", "accentHover": "#ea580c", "background": "#fffbeb", "border": "#fde68a", "borderSubtle": "#fcd34d", "error": "#dc2626", "info": "#2563eb", "overlay": "#80451a03", "primary": "#b45309", "primaryHover": "#92400e", "primaryText": "#ffffff", "success": "#16a34a", "surface": "#fef3c7", "surfaceActive": "#fcd34d", "surfaceHover": "#fde68a", "text": "#451a03", "textMuted": "#78350f", "textSubtle": "#92400e", "warning": "#d97706" },
        "light.cool": { "accent": "#0ea5e9", "accentHover": "#0284c7", "background": "#f0f9ff", "border": "#bae6fd", "borderSubtle": "#7dd3fc", "error": "#dc2626", "info": "#2563eb", "overlay": "#800c4a6e", "primary": "#0284c7", "primaryHover": "#0369a1", "primaryText": "#ffffff", "success": "#16a34a", "surface": "#e0f2fe", "surfaceActive": "#7dd3fc", "surfaceHover": "#bae6fd", "text": "#0c4a6e", "textMuted": "#0369a1", "textSubtle": "#0284c7", "warning": "#d97706" },
        "light.paper": { "accent": "#b7791f", "accentHover": "#975f13", "background": "#faf6ef", "border": "#e0d8ca", "borderSubtle": "#ece5d9", "error": "#b83227", "info": "#2b6cb0", "overlay": "#59000000", "primary": "#3b3630", "primaryHover": "#2a2621", "primaryText": "#faf6ef", "success": "#4d7c2a", "surface": "#f2ece1", "surfaceActive": "#ddd3c2", "surfaceHover": "#e8e0d2", "text": "#3b3630", "textMuted": "#6b6257", "textSubtle": "#918778", "warning": "#b7791f" },
        "light.frost": { "accent": "#2b7fd4", "accentHover": "#1d63ab", "background": "#f5f8fa", "border": "#dbe3ea", "borderSubtle": "#eaf0f5", "error": "#c53030", "info": "#2b7fd4", "overlay": "#590f172a", "primary": "#1f2933", "primaryHover": "#111820", "primaryText": "#ffffff", "success": "#2f855a", "surface": "#ffffff", "surfaceActive": "#dbe5ee", "surfaceHover": "#eaf0f5", "text": "#1f2933", "textMuted": "#52616b", "textSubtle": "#7b8794", "warning": "#b7791f" }
    })

    /** Falls back to the default of the current mode, so a stale setting cannot blank the UI. */
    readonly property var active: palettes[mode + "." + variant]
                                  || palettes[mode === "dark" ? "dark.zinc" : "light.neutral"]

    readonly property bool isDark: mode === "dark"

    readonly property color accent: active.accent
    readonly property color accentHover: active.accentHover
    readonly property color background: active.background
    readonly property color border: active.border
    readonly property color borderSubtle: active.borderSubtle
    readonly property color error: active.error
    readonly property color info: active.info
    readonly property color overlay: active.overlay
    readonly property color primary: active.primary
    readonly property color primaryHover: active.primaryHover
    readonly property color primaryText: active.primaryText
    readonly property color success: active.success
    readonly property color surface: active.surface
    readonly property color surfaceActive: active.surfaceActive
    readonly property color surfaceHover: active.surfaceHover
    readonly property color text: active.text
    readonly property color textMuted: active.textMuted
    readonly property color textSubtle: active.textSubtle
    readonly property color warning: active.warning

    function apply(nextMode, nextVariant) {
        mode = nextMode
        variant = nextVariant
    }

    property Settings _saved: Settings {
        category: "appearance"
        property alias mode: theme.mode
        property alias variant: theme.variant
    }
}
