#!/usr/bin/env python3
"""Generate desktop/qml/Theme.qml from the phone app's colours.

Thirteen palettes of nineteen tokens is too much to transcribe by hand and keep in step —
the first colour anyone changed on the phone would drift. Both apps therefore read the same
source: the phone imports it directly, and this writes the QML the desktop compiles in.

Run from the repository root:  python3 desktop/tools/generate-theme.py
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE = ROOT / "mobile/src/theme/colors.ts"
TARGET = ROOT / "desktop/qml/Theme.qml"


def to_qml_colour(value: str) -> str:
    """QML's colour type takes #RRGGBB or #AARRGGBB, never CSS rgba()."""
    match = re.fullmatch(r"rgba\(\s*(\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\s*\)", value.strip())
    if not match:
        return value
    r, g, b = (int(match.group(i)) for i in (1, 2, 3))
    a = round(float(match.group(4)) * 255)
    return f"#{a:02x}{r:02x}{g:02x}{b:02x}"


def main() -> int:
    src = SOURCE.read_text()

    palettes = {}
    for block in re.finditer(r"export const (\w+): ThemeColors = \{(.*?)\n\};", src, re.S):
        name, body = block.group(1), block.group(2)
        palettes[name] = {
            key: to_qml_colour(value)
            for key, value in re.findall(r"(\w+):\s*'([^']*)'", body)
        }

    def registry(kind: str) -> dict:
        found = re.search(rf"export const {kind}Themes: Record<[^>]+> = \{{(.*?)\n\}};", src, re.S)
        return dict(re.findall(r"(\w+):\s*(\w+),", found.group(1)))

    dark, light = registry("dark"), registry("light")
    labels = dict(re.findall(r"(\w+):\s*'([^']*)',", re.search(
        r"themeDisplayNames: Record<[^>]+> = \{(.*?)\n\};", src, re.S).group(1)))

    keys = sorted({key for palette in palettes.values() for key in palette})
    missing = {
        f"{const}.{key}"
        for const in list(dark.values()) + list(light.values())
        for key in keys if key not in palettes[const]
    }
    if missing:
        print(f"error: palettes are missing tokens: {sorted(missing)}", file=sys.stderr)
        return 1

    def emit(mapping: dict, mode: str) -> str:
        rows = []
        for variant, const in mapping.items():
            fields = ", ".join(f'"{k}": "{palettes[const][k]}"' for k in keys)
            rows.append(f'        "{mode}.{variant}": {{ {fields} }}')
        return ",\n".join(rows)

    def variant_list(mapping: dict) -> str:
        return ", ".join(
            f'{{ "id": "{v}", "label": "{labels.get(v, v)}" }}' for v in mapping)

    properties = "\n".join(f"    readonly property color {k}: active.{k}" for k in keys)

    TARGET.write_text(f'''pragma Singleton
import QtCore
import QtQuick

/**
 * The phone app's palettes.
 *
 * GENERATED by desktop/tools/generate-theme.py from mobile/src/theme/colors.ts — edit the
 * colours there and re-run it, not this file. Both apps then show the same thing, which is
 * the whole reason a toolkit that lets us set every colour was chosen.
 *
 * The choice is remembered between runs rather than resetting to the default each launch.
 */
QtObject {{
    id: theme

    property string mode: "dark"
    property string variant: "zinc"

    readonly property var darkVariants: [{variant_list(dark)}]
    readonly property var lightVariants: [{variant_list(light)}]
    readonly property var variants: mode === "dark" ? darkVariants : lightVariants

    readonly property var palettes: ({{
{emit(dark, "dark")},
{emit(light, "light")}
    }})

    /** Falls back to the default of the current mode, so a stale setting cannot blank the UI. */
    readonly property var active: palettes[mode + "." + variant]
                                  || palettes[mode === "dark" ? "dark.zinc" : "light.neutral"]

    readonly property bool isDark: mode === "dark"

{properties}

    function apply(nextMode, nextVariant) {{
        mode = nextMode
        variant = nextVariant
    }}

    property Settings _saved: Settings {{
        category: "appearance"
        property alias mode: theme.mode
        property alias variant: theme.variant
    }}
}}
''')
    print(f"wrote {TARGET.relative_to(ROOT)}: "
          f"{len(dark) + len(light)} palettes, {len(keys)} tokens each")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
